[package]
name = "PARALELOPIPEDO_CONCURRENTES_TP2"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "lib"
path = "src/lib.rs"


[dependencies]
ctrlc = { version = "3.0", features = ["termination"] }
rand = "0.8.4"
